---
title: Report on data in AusTraits
output:
  html_document:
    df_print: kable
    highlight: tango
    keep_md: no
    smart: no
    theme: yeti
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
editor_options:
  chunk_output_type: console
---

Load data
```{r}
# Install dependencies as needed
# devtools::install_deps()

# Load packages and functions for this analysis
devtools::load_all()

# load data
austraits <- readRDS("data/austraits_2.1.0.9000.rds")

au_bioclim <- load_climate_data()

# match with climate data
au_sites_clim <-
  austraits$sites %>%
  filter(site_property %in% c("longitude (deg)", "latitude (deg)")) %>%
  spread(site_property, value) %>%
  rowid_to_column("ID") %>%
  rename(latitude = `latitude (deg)`, longitude = `longitude (deg)`) %>%
  mutate_at(c("latitude", "longitude"), ~suppressWarnings(as.numeric(.x))) %>%
  combine_occurence_climate(au_bioclim)
```

Select subset of traits:
```{r}
# add max height, N_area, delta13_c
# Also do for some alternatives: e.g. leaf_width, leaf_area ?
trait_names <- c("leaf_width","leaf_delta13C","leaf_N_per_area","plant_height","specific_leaf_area", "wood_density", "leaf_area", "seed_mass")

traits <- 
  austraits$traits %>%
  filter(trait_name %in% trait_names) %>%
  left_join(au_sites_clim) 

traits_site_summary <- 
  traits %>% 
  group_by(dataset_id, trait_name, latitude, longitude, Temp, Prec) %>% 
  summarise(nspp=n_distinct(taxon_name))

```

Write some summaries about availability of data.....


Plots:

```{r, fig.height=12, fig.width=6}
austraits_climate_space <-
  plot_climate_space(traits, au_bioclim)

austraits_site_by_trait <-
  plot_site_map_by_trait(traits)

austraits_climate_space / austraits_site_by_trait
```

Shading of points (blue -> yellow) indicates the number of neighbouring points (e.g. there is substantial seed mass data in SE Australia)

Compare the number of observations and taxa for each trait which are **georeferenced vs. not georeferenced**.

```{r}
number_observations_per_trait<-traits %>%
  group_by(trait_name) %>%
  summarise(n_total_obs=length(value), n_total_taxa=length(unique(taxon_name)))

number_observations_per_trait_georeferenced<-traits %>%
  drop_na(latitude,longitude) %>%
  group_by(trait_name) %>%
  summarise(n_georef_obs=length(value), n_georef_taxa=length(unique(taxon_name))) %>%
  left_join(number_observations_per_trait) %>%
  relocate(n_total_obs, .after=trait_name) %>%
  relocate(n_total_taxa, .before=n_georef_taxa)

number_observations_per_trait_georeferenced %>%
  kbl(caption = "Note that taxa which have georeferenced and non-georeferenced values for a given trait will appear under n_georef_taxa") %>%
  kable_classic(full_width = T, html_font = "Cambria")  

```