---
title: "availability_of_euc_traits"
author: "Isaac Towers"
date: "23/06/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("R/plotting_functions.R")

austraits_develop <- readRDS("data/austraits_develop_recent.RDS")
```

```{r}
library(ozmaps)
library(sf)

austraits_develop$sites %>%
  pivot_wider(names_from = site_property, values_from = value) %>%
  select(dataset_id, site_name, `latitude (deg)`, `longitude (deg)`) -> austraits_sites_wide

austraits_develop$traits %>%
  left_join(austraits_sites_wide) -> austraits_develop_traits

austraits_develop_traits%>%
  filter(grepl(paste(c("Eucalyptus", "Corymbia", "Angophora"), collapse="|"), taxon_name)) %>% 
  filter(trait_name %in% c("plant_height","seed_dry_mass","leaf_area","specific_leaf_area", "bark_thickness", "wood_density")) %>%
  select(trait_name, taxon_name, value) %>%
  group_by(trait_name, taxon_name) %>%
  mutate(value = as.numeric(value)) %>%
  summarise(value = mean(value)) %>%
  pivot_wider(names_from = trait_name, values_from = value)-> data_wide

data_wide %>%
  select(-bark_thickness) %>%
  drop_na() %>% View()

austraits_develop_traits%>%
  filter(grepl(paste(c("Eucalyptus", "Corymbia", "Angophora"), collapse="|"), taxon_name)) %>% 
  filter(trait_name %in% c("wood_density"), !is.na(value))  %>% 
  pull(taxon_name) %>%
  unique(.) %>%
  sort()

data_wide %>%
  lapply(is.na) %>%
  lapply(sum) %>%
  unlist()

data_wide %>%
  nrow()
  
  group_by(trait_name) %>%
  summarise(trait_count = n_distinct(taxon_name)) %>%
  arrange(desc(trait_count)) %>% 
  View()

plant height
leaf area
specific leaf area
seed mass
bark thickness
stem density
  

```

